### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by AllanCerveaux** [ldevernay/sos-vue#1]
Il faut que l'utilisateur puisse rechercher un projet par : 
 - son titre
 - le langage utilisée
 - la framework/lib utilisée

**Comment by ldevernay** [comment]
Plus simple : on fait la recherche par nom de projet.
Pour la recherche par langage, passer par les tags.
Pour les librairies et les frameworks, ce n'est pas implémenté pour l'instant, de toute façon.
