### ISSUE TITLE
CI to heroku

### ISSUE THREAD

**Issue by ldevernay** [ldevernay/sos-vue#15]
Website should be deployed to heroku or surge.
It should be automatic every time something is pushed to the master branch.

**Comment by ldevernay** [comment]
Maybe a nice occasion to use github hooks.

**Comment by AllanCerveaux** [comment]
I install `git-scripts & surge` to deploy on surge [deploying continuously using git hooks](https://surge.sh/help/deploying-continuously-using-git-hooks)
